import type { SpecBundle } from '../types/spec.js';
import type { GeneratedFile, TemplateHelpers } from '../types/generator.js';

export interface GeneratorConfig {
  spec: SpecBundle;
  helpers: TemplateHelpers;
  rootDir: string;
}

export abstract class BaseGenerator {
  protected spec: SpecBundle;
  protected helpers: TemplateHelpers;
  protected rootDir: string;

  constructor(config: GeneratorConfig) {
    this.spec = config.spec;
    this.helpers = config.helpers;
    this.rootDir = config.rootDir;
  }

  abstract generate(): Promise<GeneratedFile[]>;

  protected createFile(path: string, content: string): GeneratedFile {
    return {
      path,
      content,
      overwritten: false,
    };
  }

  protected indent(code: string, spaces: number): string {
    const indent = ' '.repeat(spaces);
    return code
      .split('\n')
      .map((line) => (line.trim() ? indent + line : line))
      .join('\n');
  }

  protected generateHeader(description: string): string {
    return `/**
 * ${description}
 *
 * THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
 * Generated by Foundation Dev CLI
 * Spec version: ${this.spec.product.version}
 * Generated at: ${new Date().toISOString()}
 */

`;
  }
}
